### ISSUE TITLE
Colab link not working

### ISSUE THREAD

**Issue by sahoo-rk** [kiharalab/Domain-PFP#3]
The Colab link (https://bit.ly/domain-pfp-colab) seems broken. Could you provide the full link of the colab page.

thanks,
sahoo

**Comment by nibtehaz** [comment]
Hi @sahoo-rk , thank you for your interest in our project. 

I just check the link seems to work for me, would you please clarify what do you see when you visit the link?

Regardless, this is the current version of the colab notebook [https://colab.research.google.com/drive/1deCZzlqq-9Y-ELDUWXRyuTmfHsSBFGlU?usp=sharing](https://colab.research.google.com/drive/1deCZzlqq-9Y-ELDUWXRyuTmfHsSBFGlU?usp=sharing) . When you try https://bit.ly/domain-pfp-colab , it redirects to this notebook.

Please let me know if you need any additional help. Thanks

**Comment by sahoo-rk** [comment]
@nibtehaz Thanks for the prompt reply. I realized that the short link not working in my institution intranet. Good that you shared the full colab link. It works fine now. Thanks.

**Comment by nibtehaz** [comment]
Glad to hear that, it is possible that some networks block bit.ly 

I am closing this issue, please feel free to reach out if you need anything else.
